### PR TITLE
Update: Added the ability to use httppush sensor in PRTG 

### PR DESCRIPTION
**Pull request by vMarkusK**
Reference: #87

### CODE REVIEW

**Comment by vMarkusK** [comment]
grafik

**Comment by vMarkusK** [comment]
Original comment from @Jannos-443 :

> collect output in variable.
> added http push functionality.
>
> http push allows the script to be executed on the Veeam Server as scheduled task without the need for additional access through PRTG.
>
>benefits:
> - security (no prtg access to the backup system)
> - less prtg load because the script just sends the xml result as http
> -  no 32bit problems

**Comment by Jannos-443** [comment]
I think the problem with Hardening is that PRTG will give you no good response on the Input error. Check it in the Script would help the users

**Comment by vMarkusK** [comment]
Test with PRTG 22.1.74.1869+ and Veeam BR v12 Beta 1 successful (httpPush and EXE/XML Sensor)

**Comment by vMarkusK** [comment]
> I think the problem with Hardening is that PRTG will give you no good response on the Input error. Checking it in the Script and use the PRTG error output would help the users

I agree with that. It's a bit cosmetic...

**Comment by vMarkusK** [comment]
@Jannos-443  any specific reason why you have chosen the Request Method GET and not POST?

**Pull request merged**
