### PR TITLE
Added the ability to use httppush sensor in PRTG

### PR DESCRIPTION
**Pull request by Jannos-443**
collect output in variable.
added http push functionality.

http push allows the script to be executed on the Veeam Server as scheduled task without the need for additional access through PRTG. 

benefits
- security (no prtg access to the backup system)
- less prtg load because the script just sends the xml result as http
- no 32bit problems

### CODE REVIEW

**Comment by vMarkusK** [comment]
This is an awesome idea! Thanks for your contribution.

I will have a look at this as soon as my lab us up and running again.

**Comment by vMarkusK** [comment]
Would it possibly make sense to create a whole new script and freeze the current one like it is due to the large number of new features?

The new one then only for http push.

**Comment by Jannos-443** [comment]
here is a Version with some changes :) https://github.com/Jannos-443/PRTG-Veeam-Status

**Review by vMarkusK — CHANGES_REQUESTED** [review]
Rename Script to Veeam/PRTG-VeeamBRStats-v2.ps1 and add the original version as Veeam/PRTG-VeeamBRStats.ps1

**Comment by vMarkusK** [comment]
Hi @Jannos-443 ,

I think it's the best solution to start a new Version with your changes and keep the original script for current users. All new development will then continue in v2. What do you think about that?

I currently spin up a new v12 Beta + PRTG lab to verify the changes.

**Comment by vMarkusK** [comment]
duplicates #90

**Pull request closed without merging**
